# Generated by Django 3.2.6 on 2021-09-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_comment_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='flActive',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='watchers',
        ),
    ]
