# Generated by Django 3.2.6 on 2021-09-20 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='buyer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
