# Generated by Django 3.2.6 on 2021-09-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='buyer',
            new_name='user',
        ),
    ]
