# Generated by Django 3.2.6 on 2021-09-26 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_listing_watchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='finalBuyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalBuyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
