# Generated by Django 3.2.6 on 2021-09-26 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_finalbuyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='finalBuyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalBuyer', to=settings.AUTH_USER_MODEL),
        ),
    ]
